# LOG
logging:
  level:
    org.springframework.security: INFO
    root: INFO

# 服务注册
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://yczd-server-eureka:8761/eureka/
      
# 配置服务
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: 'yczd-server-config'
      password: password
      username: user
      fail-fast: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://yczd-api-auth:5000/uaa/users/current

#spring:
#  rabbitmq:
#    host: rabbitmq
