server:
  port: 4000
  servlet:
    context-path: /
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true 

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    yczd-api-auth:
        path: /auth/**
        serviceId: yczd-api-auth
        stripPrefix: false
        sensitiveHeaders:

    #account-service:
    #    path: /accounts/**
    #    serviceId: account-service
    #    stripPrefix: false
    #    sensitiveHeaders:

    #statistics-service:
    #    path: /statistics/**
    #    serviceId: statistics-service
    #    stripPrefix: false
    #    sensitiveHeaders:

    #notification-service:
    #    path: /notifications/**
    #    serviceId: notification-service
    #    stripPrefix: false
    #    sensitiveHeaders:
 
