# 默认开发环境
spring:
  profiles:
    active: dev

# 公共配置
  application:
    name: yczd-api-aio

mybatis:
  config-location: classpath:mybatis-config.xml

---
# 开发环境
spring:
  profiles: dev
  # H2和MySql的切换:修改下面配置
  datasource:
    # H2 Data Source
    # schema: classpath:/db/migration/h2/v0_1_ddl_init.sql
    # MySQL设定
    url: ${mysql_url:jdbc:mysql://localhost:3306/yczd-mini}
    username: ${username:root}
    password: ${password:admin}
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

---
# 测试环境
spring:
  profiles: test 
  datasource:
    url: ${mysql_url:jdbc:mysql://localhost:3306/yczd-mini}
    username: ${username:root}
    password: ${password:admin}
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

---
# 生产环境
spring:
  profiles: prod
  
  datasource:
    url: ${mysql_url:jdbc:mysql://localhost:3306/yczd-mini}
    username: ${username:root}
    password: ${password:admin}
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
